plugins {
    id 'com.android.library'
    alias(libs.plugins.kotlin.android)
}

android {
    compileSdk rootProject.ext.compileSdkVersion

    defaultConfig {
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
        multiDexEnabled true
        manifestPlaceholders = [
                //易平方
                GOOGLE_MAPS_API_KEY     : "AIzaSyAhmfiKGA7TUWN_vyCY7P3kgsAutIhppAU",
                GOOGLE_DIRECTION_API_KEY: "AIzaSyDrS1LykCaZ1_GV4o8zWfYl-GDbRPEpoVA"
        ]
    }

    buildFeatures {
        buildConfig true
    }

    publishNonDefault true
    flavorDimensions "versionCode"
    productFlavors {
//        aTestOkla {
//            dimension "versionCode"
//            buildConfigField("String", "BASE_URL", "\"https://t-kora-admin-app.esquare-global.com/\"")
//            //测试服务器
//            buildConfigField("String", "USER_AGREEMENT", "\"https://t-kora-h5-web.esquare-global.com/agreement/agreement.html\"")
//            buildConfigField("String", "PRIVACY_POLICY", "\"https://t-kora-h5-web.esquare-global.com/agreement/privacyAgreement.html\"")
//            buildConfigField("String", "USER_AGREEMENT_FR", "\"https://za-kora-h5-web.esquare-global.com/agreement/agreementFr.html\"")
//            buildConfigField("String", "PRIVACY_POLICY_FR", "\"https://za-kora-h5-web.esquare-global.com/agreement/privacyAgreementFr.html\"")
//
//        }
        onlineOkla {
            dimension "versionCode"
            buildConfigField("String", "BASE_URL", "\"https://okla-admin-app.esquare-global.com\"")
            buildConfigField("String", "USER_AGREEMENT", "\"https://za-h5-web.esquare-global.com/okla/userAppAgreement.html?appId=okla\"")
            buildConfigField("String", "PRIVACY_POLICY", "\"https://za-h5-web.esquare-global.com/okla/privacyAgreement.html\"")
        }
    }
    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildFeatures {
        viewBinding = false
        dataBinding = true
    }
    namespace 'com.base.common'
    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation libs.androidx.core.ktx
    implementation libs.androidx.lifecycle.viewmodel.ktx
    coreLibraryDesugaring libs.desugar.jdk.libs

    testImplementation libs.junit
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.espresso.core
    api libs.androidx.datastore.preferences
    api libs.cymchad.baserecyclerviewadapterhelper
    api libs.smartrefreshlayout
    api libs.photoview
    api libs.eventbus
    api libs.glide
    implementation libs.fresco
    implementation libs.glide
    annotationProcessor libs.compiler
    api libs.rxpermissions
//    api libs.banner
    api libs.flexbox

    //---4.4以上沉浸式实现----------------------------------
    // 基础依赖包，必须要依赖
    api libs.immersionbar

    //room
    api libs.room.runtime
    annotationProcessor libs.androidx.room.compiler
    api libs.androidx.room.rxjava2

    //弹窗
    api libs.basepopup
    api libs.xpopup

    //图库
    api libs.pictureselector
    api libs.compress
    api libs.ucrop
    api libs.camerax
    //拍照
    api libs.album

//    //扫码
//    api libs.scanplus
    api libs.zxingembedded
    api libs.googlezxing

    //google map
    api(libs.places)
    api(libs.play.services.maps)
    api(libs.play.services.gcm)
    api(libs.play.services.location)
    api(libs.auto.value.annotations)

    api project(':library')

}