name: merchant_app_workspace

packages:
  - .
  - packages/**

scripts:
  bootstrap:
    description: Install dependencies in all workspace packages.
    run: melos bootstrap

  analyze:
    description: Run static analysis in all Flutter packages.
    run: melos exec -- "flutter analyze"

  test:
    description: Run tests in all packages that include tests.
    run: melos exec --fail-fast --dir-exists=test -- "flutter test"
