import 'dart:io';

void main(List<String> args) {
  final name = _readArg(args, '--name');
  final description = _readArg(args, '--description') ?? 'Feature module generated by scaffold_feature.';

  if (name == null || name.isEmpty) {
    stderr.writeln('Usage: dart run tools/scaffold_feature.dart --name feature_xxx [--description "..."]');
    exit(2);
  }

  if (!name.startsWith('feature_')) {
    stderr.writeln('Feature package name must start with feature_.');
    exit(2);
  }

  final root = Directory.current;
  final packageDir = Directory('${root.path}/packages/$name');
  if (packageDir.existsSync()) {
    stderr.writeln('Package already exists: ${packageDir.path}');
    exit(1);
  }

  final featureStem = name.substring('feature_'.length);
  final classStem = _toPascalCase(featureStem);
  final routeClass = '${classStem}RoutePaths';
  final contractClass = '${classStem}FeatureContract';
  final moduleClass = '${classStem}FeatureModule';
  final pageClass = '${classStem}TabPage';

  Directory('${packageDir.path}/lib/src').createSync(recursive: true);
  Directory('${packageDir.path}/test').createSync(recursive: true);

  _write(
    '${packageDir.path}/pubspec.yaml',
    _pubspec(name: name, description: description),
  );
  _write('${packageDir.path}/lib/$name.dart', _entry(name: name));
  _write(
    '${packageDir.path}/lib/src/${featureStem}_route_paths.dart',
    _routePaths(routeClass: routeClass, featureStem: featureStem),
  );
  _write(
    '${packageDir.path}/lib/src/${featureStem}_feature_contract.dart',
    _contract(contractClass: contractClass),
  );
  _write(
    '${packageDir.path}/lib/src/${featureStem}_feature_module.dart',
    _module(
      routeClass: routeClass,
      contractClass: contractClass,
      moduleClass: moduleClass,
      pageClass: pageClass,
      featureStem: featureStem,
    ),
  );
  _write(
    '${packageDir.path}/lib/src/${featureStem}_tab_page.dart',
    _page(pageClass: pageClass, classStem: classStem),
  );
  _write(
    '${packageDir.path}/test/${featureStem}_feature_module_test.dart',
    _test(
      packageName: name,
      moduleClass: moduleClass,
      routeClass: routeClass,
      featureStem: featureStem,
    ),
  );

  stdout.writeln('Created package: packages/$name');
  stdout.writeln('Next steps:');
  stdout.writeln('1. melos bootstrap');
  stdout.writeln('2. Register module in app_shell route assembly if needed.');
  stdout.writeln('3. Run melos run analyze && melos run test');
}

String? _readArg(List<String> args, String key) {
  for (var i = 0; i < args.length; i++) {
    if (args[i] == key && i + 1 < args.length) {
      return args[i + 1];
    }
    if (args[i].startsWith('$key=')) {
      return args[i].substring(key.length + 1);
    }
  }
  return null;
}

String _toPascalCase(String value) {
  return value
      .split('_')
      .where((e) => e.isNotEmpty)
      .map((e) => e[0].toUpperCase() + e.substring(1))
      .join();
}

void _write(String path, String content) {
  File(path).writeAsStringSync(content);
}

String _pubspec({required String name, required String description}) {
  return '''name: $name
description: $description
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.8.1
  design_system:
    path: ../design_system
  foundation:
    path: ../foundation

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
''';
}

String _entry({required String name}) {
  final featureStem = name.substring('feature_'.length);
  return '''library;

export 'src/${featureStem}_feature_contract.dart';
export 'src/${featureStem}_feature_module.dart';
export 'src/${featureStem}_route_paths.dart';
export 'src/${featureStem}_tab_page.dart';
''';
}

String _routePaths({required String routeClass, required String featureStem}) {
  return '''class $routeClass {
  const $routeClass._();

  static const String root = '/$featureStem';
}
''';
}

String _contract({required String contractClass}) {
  return '''import 'package:go_router/go_router.dart';

class $contractClass {
  const $contractClass({required this.routes});

  final List<RouteBase> routes;
}
''';
}

String _module({
  required String routeClass,
  required String contractClass,
  required String moduleClass,
  required String pageClass,
  required String featureStem,
}) {
  return '''import 'package:go_router/go_router.dart';

import '${featureStem}_feature_contract.dart';
import '${featureStem}_route_paths.dart';
import '${featureStem}_tab_page.dart';

class $moduleClass {
  $moduleClass();

  final $contractClass contract = $contractClass(
    routes: [
      GoRoute(
        path: $routeClass.root,
        builder: (context, state) => const $pageClass(),
      ),
    ],
  );
}
''';
}

String _page({required String pageClass, required String classStem}) {
  return '''import 'package:flutter/material.dart';

class $pageClass extends StatelessWidget {
  const $pageClass({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(
        child: Text('$classStem Feature'),
      ),
    );
  }
}
''';
}

String _test({
  required String packageName,
  required String moduleClass,
  required String routeClass,
  required String featureStem,
}) {
  return '''import 'package:$packageName/$packageName.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  test('$moduleClass exposes route contract', () {
    final module = $moduleClass();

    expect(module.contract.routes, isNotEmpty);
    expect(
      module.contract.routes
          .whereType<dynamic>()
          .map((route) => route.path)
          .toSet(),
      contains($routeClass.root),
    );
  });
}
''';
}
